services:
  db:
    image: mysql:8.0
    container_name: woocker_db
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wordpress}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
    networks:
      - wordpress-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-rootpassword}"]
      timeout: 20s
      retries: 10

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORDPRESS_VERSION: ${WORDPRESS_VERSION:-6.4}
        PHP_VERSION: ${PHP_VERSION:-8.1}
        WORDPRESS_IMAGE_TAG: ${WORDPRESS_IMAGE_TAG}
    container_name: woocker_wordpress
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${WORDPRESS_PORT:-8000}:80"
    volumes:
      # Mount entire WordPress directory for local development
      - ./wordpress:/var/www/html
      - ./scripts:/var/www/scripts
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-wordpress}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-1}
      WORDPRESS_DEBUG_LOG: ${WORDPRESS_DEBUG_LOG:-1}
      WORDPRESS_DEBUG_DISPLAY: ${WORDPRESS_DEBUG_DISPLAY:-0}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_ENVIRONMENT_TYPE', 'local');
        define('SCRIPT_DEBUG', true);
        define('SAVEQUERIES', true);
      XDEBUG_MODE: ${XDEBUG_MODE:-debug}
      XDEBUG_CONFIG: client_host=${XDEBUG_CLIENT_HOST:-host.docker.internal} client_port=${XDEBUG_CLIENT_PORT:-9003} idekey=${XDEBUG_IDE_KEY:-PHPSTORM}
      PHP_IDE_CONFIG: serverName=${WORDPRESS_HOSTNAME:-localhost}
    networks:
      - wordpress-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: woocker_phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
    networks:
      - wordpress-network

volumes:
  db_data:

networks:
  wordpress-network:
    driver: bridge
